### PR TITLE
Remove references to gnosis.io domain

### PR DESCRIPTION
**Pull request by fmrsabino**
- Replaces `gnosis.io` references with `safe.global`
- Changes the authors email @rmeissner and @fmrsabino with a `safe.global` email
- Updates README.md links:
  * Swagger now points to https://safe-client.safe.global/index.html
  * Safe developer documentation now points to https://docs.gnosis-safe.io/

### CODE REVIEW

**Comment by fmrsabino** [comment]
Pipeline fails because of a linking issue on the newer `ubuntu-latest` images – more context here: https://github.com/safe-global/safe-client-gateway/pull/1024

Once https://github.com/safe-global/safe-client-gateway/pull/1022 is merged we can rebase this changes.

**Review by moisses89 — CHANGES_REQUESTED** [review]
I think that everything looks good but several tests was changed, the issue with the image on github-actions was fixed [here](https://github.com/safe-global/safe-client-gateway/pull/1024) then could you rebase to see if this PR pass the test suite.

**Comment by fmrsabino** [comment]
> I think that everything looks good but several tests was changed, the issue with the image on github-actions was fixed [here](https://github.com/safe-global/safe-client-gateway/pull/1024) then could you rebase to see if this PR pass the test suite.

I commented about this here: https://github.com/safe-global/safe-client-gateway/pull/1026#issuecomment-1339456645

**Review by rmeissner — APPROVED** [review]

**Review by moisses89 — APPROVED** [review]
Looks good for me :)

**Pull request merged**
